repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        args: [ "--whitespaces-count", "4" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [
            "--profile", "black",
            "--line-length", "80"
        ]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [
          "--safe",
          "--line-length", "80"
      ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [
            "--max-line-length", "80",
            "--extend-ignore", "D105,D107,D205,D212,D415",
            "--exclude", ".eggs,.git,__pycache__,.tox,.vscode,build/,dist/",
            "--docstring-convention", "google"
        ]
        language_version: python3
        additional_dependencies:
          - flake8-docstrings==1.5.0
